[build.environment]
  HUGO_VERSION = "0.130.0"

# https://docs.netlify.com/routing/redirects/#syntax-for-the-netlify-configuration-file

[[redirects]]
  from = "/docs/memory-safety"
  to = "https://www.memorysafety.org/docs/memory-safety"
  status = 301
  force = false

[[redirects]]
  from = "/divviup"
  to = "https://divviup.org"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  force = false

[[redirects]]
  from = "https://isrg.org/*"
  to = "https://abetterinternet.org/:splat"
  status = 302
  force = true

[[redirects]]
  from = "https://www.isrg.org/*"
  to = "https://abetterinternet.org/:splat"
  status = 302
  force = true
